name: Deploy to Lightsail

on:
 push:
   branches:
     - main

jobs:
 deploy:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout
     uses: actions/checkout@v3

   - name: Deploy to Lightsail
     uses: appleboy/ssh-action@master
     with:
       host: ${{ secrets.SERVER_HOST }}
       username: ${{ secrets.SERVER_USER }}
       key: ${{ secrets.SERVER_KEY }}
       script: |
         cd ~/vive_pptgen_be
         git pull
         chmod +x deploy.sh
         ./deploy.sh
         exit 0
